// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_secrets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addApiSecretSubscriber = `-- name: AddApiSecretSubscriber :exec
INSERT INTO api_secret_subscribers (api_secret_id, subscriber_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddApiSecretSubscriberParams struct {
	ApiSecretID  pgtype.UUID
	SubscriberID pgtype.UUID
}

func (q *Queries) AddApiSecretSubscriber(ctx context.Context, arg AddApiSecretSubscriberParams) error {
	_, err := q.db.Exec(ctx, addApiSecretSubscriber, arg.ApiSecretID, arg.SubscriberID)
	return err
}

const deleteApiSecret = `-- name: DeleteApiSecret :exec
DELETE FROM api_secrets WHERE id = $1
`

func (q *Queries) DeleteApiSecret(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteApiSecret, id)
	return err
}

const getApiSecretByID = `-- name: GetApiSecretByID :one
SELECT id, name, secret_hash, subject_pattern, created_at FROM api_secrets WHERE id = $1
`

func (q *Queries) GetApiSecretByID(ctx context.Context, id pgtype.UUID) (ApiSecret, error) {
	row := q.db.QueryRow(ctx, getApiSecretByID, id)
	var i ApiSecret
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SecretHash,
		&i.SubjectPattern,
		&i.CreatedAt,
	)
	return i, err
}

const getApiSecretSubscriberExists = `-- name: GetApiSecretSubscriberExists :one
SELECT EXISTS(
    SELECT 1 FROM api_secret_subscribers
    WHERE api_secret_id = $1 AND subscriber_id = $2
) AS exists
`

type GetApiSecretSubscriberExistsParams struct {
	ApiSecretID  pgtype.UUID
	SubscriberID pgtype.UUID
}

func (q *Queries) GetApiSecretSubscriberExists(ctx context.Context, arg GetApiSecretSubscriberExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, getApiSecretSubscriberExists, arg.ApiSecretID, arg.SubscriberID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertApiSecret = `-- name: InsertApiSecret :one
INSERT INTO api_secrets (id, name, secret_hash, subject_pattern, created_at)
VALUES ($1, $2, $3, $4, now())
RETURNING id, name, secret_hash, subject_pattern, created_at
`

type InsertApiSecretParams struct {
	ID             pgtype.UUID
	Name           string
	SecretHash     string
	SubjectPattern string
}

func (q *Queries) InsertApiSecret(ctx context.Context, arg InsertApiSecretParams) (ApiSecret, error) {
	row := q.db.QueryRow(ctx, insertApiSecret,
		arg.ID,
		arg.Name,
		arg.SecretHash,
		arg.SubjectPattern,
	)
	var i ApiSecret
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SecretHash,
		&i.SubjectPattern,
		&i.CreatedAt,
	)
	return i, err
}

const listAllApiSecretHashes = `-- name: ListAllApiSecretHashes :many
SELECT id, secret_hash, subject_pattern FROM api_secrets
`

type ListAllApiSecretHashesRow struct {
	ID             pgtype.UUID
	SecretHash     string
	SubjectPattern string
}

func (q *Queries) ListAllApiSecretHashes(ctx context.Context) ([]ListAllApiSecretHashesRow, error) {
	rows, err := q.db.Query(ctx, listAllApiSecretHashes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllApiSecretHashesRow
	for rows.Next() {
		var i ListAllApiSecretHashesRow
		if err := rows.Scan(&i.ID, &i.SecretHash, &i.SubjectPattern); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApiSecrets = `-- name: ListApiSecrets :many
SELECT
    s.id, s.name, s.secret_hash, s.subject_pattern, s.created_at,
    COALESCE(
        string_agg(sub.name, ', ' ORDER BY sub.name),
        ''
    )::text AS subscriber_names
FROM api_secrets s
LEFT JOIN api_secret_subscribers ass ON ass.api_secret_id = s.id
LEFT JOIN subscribers sub ON sub.id = ass.subscriber_id
GROUP BY s.id
ORDER BY s.created_at DESC
`

type ListApiSecretsRow struct {
	ID              pgtype.UUID
	Name            string
	SecretHash      string
	SubjectPattern  string
	CreatedAt       pgtype.Timestamptz
	SubscriberNames string
}

func (q *Queries) ListApiSecrets(ctx context.Context) ([]ListApiSecretsRow, error) {
	rows, err := q.db.Query(ctx, listApiSecrets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApiSecretsRow
	for rows.Next() {
		var i ListApiSecretsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SecretHash,
			&i.SubjectPattern,
			&i.CreatedAt,
			&i.SubscriberNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApiSecretsForSubscriber = `-- name: ListApiSecretsForSubscriber :many
SELECT s.id, s.name, s.secret_hash, s.subject_pattern, s.created_at
FROM api_secrets s
JOIN api_secret_subscribers ass ON ass.api_secret_id = s.id
WHERE ass.subscriber_id = $1
ORDER BY s.created_at DESC
`

func (q *Queries) ListApiSecretsForSubscriber(ctx context.Context, subscriberID pgtype.UUID) ([]ApiSecret, error) {
	rows, err := q.db.Query(ctx, listApiSecretsForSubscriber, subscriberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiSecret
	for rows.Next() {
		var i ApiSecret
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SecretHash,
			&i.SubjectPattern,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscribersForApiSecret = `-- name: ListSubscribersForApiSecret :many
SELECT sub.id, sub.name, sub.endpoint_url, sub.auth_secret, sub.max_parallel, sub.created_at, sub.updated_at
FROM subscribers sub
JOIN api_secret_subscribers ass ON ass.subscriber_id = sub.id
WHERE ass.api_secret_id = $1
ORDER BY sub.name
`

func (q *Queries) ListSubscribersForApiSecret(ctx context.Context, apiSecretID pgtype.UUID) ([]Subscriber, error) {
	rows, err := q.db.Query(ctx, listSubscribersForApiSecret, apiSecretID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscriber
	for rows.Next() {
		var i Subscriber
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EndpointUrl,
			&i.AuthSecret,
			&i.MaxParallel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllApiSecretSubscribers = `-- name: RemoveAllApiSecretSubscribers :exec
DELETE FROM api_secret_subscribers WHERE api_secret_id = $1
`

func (q *Queries) RemoveAllApiSecretSubscribers(ctx context.Context, apiSecretID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeAllApiSecretSubscribers, apiSecretID)
	return err
}

const removeApiSecretSubscriber = `-- name: RemoveApiSecretSubscriber :exec
DELETE FROM api_secret_subscribers
WHERE api_secret_id = $1 AND subscriber_id = $2
`

type RemoveApiSecretSubscriberParams struct {
	ApiSecretID  pgtype.UUID
	SubscriberID pgtype.UUID
}

func (q *Queries) RemoveApiSecretSubscriber(ctx context.Context, arg RemoveApiSecretSubscriberParams) error {
	_, err := q.db.Exec(ctx, removeApiSecretSubscriber, arg.ApiSecretID, arg.SubscriberID)
	return err
}

const updateApiSecret = `-- name: UpdateApiSecret :one
UPDATE api_secrets SET
    name = $1,
    subject_pattern = $2
WHERE id = $3
RETURNING id, name, secret_hash, subject_pattern, created_at
`

type UpdateApiSecretParams struct {
	Name           string
	SubjectPattern string
	ID             pgtype.UUID
}

func (q *Queries) UpdateApiSecret(ctx context.Context, arg UpdateApiSecretParams) (ApiSecret, error) {
	row := q.db.QueryRow(ctx, updateApiSecret, arg.Name, arg.SubjectPattern, arg.ID)
	var i ApiSecret
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SecretHash,
		&i.SubjectPattern,
		&i.CreatedAt,
	)
	return i, err
}
