// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEventByID = `-- name: GetEventByID :one
SELECT id, subject, timestamp, trace_id, data, retry_count, delivery_status, status_updated_at FROM events WHERE id = $1
`

func (q *Queries) GetEventByID(ctx context.Context, id pgtype.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Timestamp,
		&i.TraceID,
		&i.Data,
		&i.RetryCount,
		&i.DeliveryStatus,
		&i.StatusUpdatedAt,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (id, subject, timestamp, trace_id, data, retry_count, delivery_status, status_updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, subject, timestamp, trace_id, data, retry_count, delivery_status, status_updated_at
`

type InsertEventParams struct {
	ID              pgtype.UUID
	Subject         string
	Timestamp       pgtype.Timestamptz
	TraceID         pgtype.UUID
	Data            []byte
	RetryCount      int32
	DeliveryStatus  string
	StatusUpdatedAt pgtype.Timestamptz
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.ID,
		arg.Subject,
		arg.Timestamp,
		arg.TraceID,
		arg.Data,
		arg.RetryCount,
		arg.DeliveryStatus,
		arg.StatusUpdatedAt,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Timestamp,
		&i.TraceID,
		&i.Data,
		&i.RetryCount,
		&i.DeliveryStatus,
		&i.StatusUpdatedAt,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, subject, timestamp, trace_id, data, retry_count, delivery_status, status_updated_at FROM events ORDER BY timestamp DESC LIMIT $1 OFFSET $2
`

type ListEventsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.Timestamp,
			&i.TraceID,
			&i.Data,
			&i.RetryCount,
			&i.DeliveryStatus,
			&i.StatusUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchEventsByDataContent = `-- name: SearchEventsByDataContent :many
SELECT id, subject, timestamp, trace_id, data, retry_count, delivery_status, status_updated_at FROM events WHERE data @> $1 ORDER BY timestamp DESC LIMIT $2 OFFSET $3
`

type SearchEventsByDataContentParams struct {
	Data   []byte
	Limit  int32
	Offset int32
}

func (q *Queries) SearchEventsByDataContent(ctx context.Context, arg SearchEventsByDataContentParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, searchEventsByDataContent, arg.Data, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.Timestamp,
			&i.TraceID,
			&i.Data,
			&i.RetryCount,
			&i.DeliveryStatus,
			&i.StatusUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchEventsByDateRange = `-- name: SearchEventsByDateRange :many
SELECT id, subject, timestamp, trace_id, data, retry_count, delivery_status, status_updated_at FROM events WHERE timestamp >= $3 AND timestamp <= $4 ORDER BY timestamp DESC LIMIT $1 OFFSET $2
`

type SearchEventsByDateRangeParams struct {
	Limit     int32
	Offset    int32
	StartTime pgtype.Timestamptz
	EndTime   pgtype.Timestamptz
}

func (q *Queries) SearchEventsByDateRange(ctx context.Context, arg SearchEventsByDateRangeParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, searchEventsByDateRange,
		arg.Limit,
		arg.Offset,
		arg.StartTime,
		arg.EndTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.Timestamp,
			&i.TraceID,
			&i.Data,
			&i.RetryCount,
			&i.DeliveryStatus,
			&i.StatusUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchEventsByDeliveryStatus = `-- name: SearchEventsByDeliveryStatus :many
SELECT id, subject, timestamp, trace_id, data, retry_count, delivery_status, status_updated_at FROM events WHERE delivery_status = $1 ORDER BY timestamp DESC LIMIT $2 OFFSET $3
`

type SearchEventsByDeliveryStatusParams struct {
	DeliveryStatus string
	Limit          int32
	Offset         int32
}

func (q *Queries) SearchEventsByDeliveryStatus(ctx context.Context, arg SearchEventsByDeliveryStatusParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, searchEventsByDeliveryStatus, arg.DeliveryStatus, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.Timestamp,
			&i.TraceID,
			&i.Data,
			&i.RetryCount,
			&i.DeliveryStatus,
			&i.StatusUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchEventsBySubject = `-- name: SearchEventsBySubject :many
SELECT id, subject, timestamp, trace_id, data, retry_count, delivery_status, status_updated_at FROM events WHERE subject = $1 ORDER BY timestamp DESC LIMIT $2 OFFSET $3
`

type SearchEventsBySubjectParams struct {
	Subject string
	Limit   int32
	Offset  int32
}

func (q *Queries) SearchEventsBySubject(ctx context.Context, arg SearchEventsBySubjectParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, searchEventsBySubject, arg.Subject, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.Timestamp,
			&i.TraceID,
			&i.Data,
			&i.RetryCount,
			&i.DeliveryStatus,
			&i.StatusUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchEventsFiltered = `-- name: SearchEventsFiltered :many
SELECT id, subject, timestamp, trace_id, data, retry_count, delivery_status, status_updated_at FROM events
WHERE
  ($3::text = '' OR subject LIKE $3)
  AND ($4::text = '' OR delivery_status = $4)
  AND ($5::timestamptz IS NULL OR timestamp >= $5)
  AND ($6::timestamptz IS NULL OR timestamp <= $6)
  AND ($7::jsonb IS NULL OR data @> $7)
ORDER BY timestamp DESC LIMIT $1 OFFSET $2
`

type SearchEventsFilteredParams struct {
	Limit           int32
	Offset          int32
	SubjectFilter   string
	StatusFilter    string
	StartTimeFilter pgtype.Timestamptz
	EndTimeFilter   pgtype.Timestamptz
	DataFilter      []byte
}

func (q *Queries) SearchEventsFiltered(ctx context.Context, arg SearchEventsFilteredParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, searchEventsFiltered,
		arg.Limit,
		arg.Offset,
		arg.SubjectFilter,
		arg.StatusFilter,
		arg.StartTimeFilter,
		arg.EndTimeFilter,
		arg.DataFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.Timestamp,
			&i.TraceID,
			&i.Data,
			&i.RetryCount,
			&i.DeliveryStatus,
			&i.StatusUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEventDeliveryStatus = `-- name: UpdateEventDeliveryStatus :one
UPDATE events SET delivery_status = $1, retry_count = $2, status_updated_at = $3 WHERE id = $4 RETURNING id, subject, timestamp, trace_id, data, retry_count, delivery_status, status_updated_at
`

type UpdateEventDeliveryStatusParams struct {
	DeliveryStatus  string
	RetryCount      int32
	StatusUpdatedAt pgtype.Timestamptz
	ID              pgtype.UUID
}

func (q *Queries) UpdateEventDeliveryStatus(ctx context.Context, arg UpdateEventDeliveryStatusParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEventDeliveryStatus,
		arg.DeliveryStatus,
		arg.RetryCount,
		arg.StatusUpdatedAt,
		arg.ID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Timestamp,
		&i.TraceID,
		&i.Data,
		&i.RetryCount,
		&i.DeliveryStatus,
		&i.StatusUpdatedAt,
	)
	return i, err
}
