// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: log_config.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteLogConfigForSubject = `-- name: DeleteLogConfigForSubject :exec
DELETE FROM log_config WHERE subject = $1
`

func (q *Queries) DeleteLogConfigForSubject(ctx context.Context, subject string) error {
	_, err := q.db.Exec(ctx, deleteLogConfigForSubject, subject)
	return err
}

const getLogConfigBySubject = `-- name: GetLogConfigBySubject :one
SELECT id, subject, log_properties FROM log_config WHERE subject = $1
`

func (q *Queries) GetLogConfigBySubject(ctx context.Context, subject string) (LogConfig, error) {
	row := q.db.QueryRow(ctx, getLogConfigBySubject, subject)
	var i LogConfig
	err := row.Scan(&i.ID, &i.Subject, &i.LogProperties)
	return i, err
}

const listLogConfigs = `-- name: ListLogConfigs :many
SELECT id, subject, log_properties FROM log_config ORDER BY subject
`

func (q *Queries) ListLogConfigs(ctx context.Context) ([]LogConfig, error) {
	rows, err := q.db.Query(ctx, listLogConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogConfig
	for rows.Next() {
		var i LogConfig
		if err := rows.Scan(&i.ID, &i.Subject, &i.LogProperties); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLogConfig = `-- name: UpsertLogConfig :one
INSERT INTO log_config (id, subject, log_properties)
VALUES ($1, $2, $3)
ON CONFLICT (subject) DO UPDATE SET
    log_properties = EXCLUDED.log_properties
RETURNING id, subject, log_properties
`

type UpsertLogConfigParams struct {
	ID            pgtype.UUID
	Subject       string
	LogProperties []string
}

func (q *Queries) UpsertLogConfig(ctx context.Context, arg UpsertLogConfigParams) (LogConfig, error) {
	row := q.db.QueryRow(ctx, upsertLogConfig, arg.ID, arg.Subject, arg.LogProperties)
	var i LogConfig
	err := row.Scan(&i.ID, &i.Subject, &i.LogProperties)
	return i, err
}
