// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiSecret struct {
	ID             pgtype.UUID
	Name           string
	SecretHash     string
	SubjectPattern string
	CreatedAt      pgtype.Timestamptz
}

type ApiSecretSubscriber struct {
	ApiSecretID  pgtype.UUID
	SubscriberID pgtype.UUID
}

type DeliveryAttempt struct {
	ID                 pgtype.UUID
	EventID            pgtype.UUID
	SubscriberID       pgtype.UUID
	EndpointUrl        string
	AttemptedAt        pgtype.Timestamptz
	RequestHeaders     []byte
	ResponseStatusCode pgtype.Int4
	ResponseHeaders    []byte
	ResponseBody       string
	Status             string
}

type Event struct {
	ID              pgtype.UUID
	Subject         string
	Timestamp       pgtype.Timestamptz
	TraceID         pgtype.UUID
	Data            []byte
	RetryCount      int32
	DeliveryStatus  string
	StatusUpdatedAt pgtype.Timestamptz
}

type LogConfig struct {
	ID            pgtype.UUID
	Subject       string
	LogProperties []string
}

type Subscriber struct {
	ID          pgtype.UUID
	Name        string
	EndpointUrl string
	AuthSecret  string
	MaxParallel int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Subscription struct {
	ID             pgtype.UUID
	SubscriberID   pgtype.UUID
	SubjectPattern string
	Filter         []byte
	MaxRetries     pgtype.Int4
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
