// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscribers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (id, subscriber_id, subject_pattern, filter, max_retries, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, now(), now())
RETURNING id, subscriber_id, subject_pattern, filter, max_retries, created_at, updated_at
`

type CreateSubscriptionParams struct {
	ID             pgtype.UUID
	SubscriberID   pgtype.UUID
	SubjectPattern string
	Filter         []byte
	MaxRetries     pgtype.Int4
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.ID,
		arg.SubscriberID,
		arg.SubjectPattern,
		arg.Filter,
		arg.MaxRetries,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.SubscriberID,
		&i.SubjectPattern,
		&i.Filter,
		&i.MaxRetries,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSubscriber = `-- name: DeleteSubscriber :exec
DELETE FROM subscribers WHERE id = $1
`

func (q *Queries) DeleteSubscriber(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSubscriber, id)
	return err
}

const deleteSubscriptionsForSubscriber = `-- name: DeleteSubscriptionsForSubscriber :exec
DELETE FROM subscriptions WHERE subscriber_id = $1
`

func (q *Queries) DeleteSubscriptionsForSubscriber(ctx context.Context, subscriberID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSubscriptionsForSubscriber, subscriberID)
	return err
}

const getSubscriberByEndpointURL = `-- name: GetSubscriberByEndpointURL :one
SELECT id, name, endpoint_url, auth_secret, max_parallel, created_at, updated_at FROM subscribers WHERE endpoint_url = $1
`

func (q *Queries) GetSubscriberByEndpointURL(ctx context.Context, endpointUrl string) (Subscriber, error) {
	row := q.db.QueryRow(ctx, getSubscriberByEndpointURL, endpointUrl)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EndpointUrl,
		&i.AuthSecret,
		&i.MaxParallel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriberByID = `-- name: GetSubscriberByID :one
SELECT id, name, endpoint_url, auth_secret, max_parallel, created_at, updated_at FROM subscribers WHERE id = $1
`

func (q *Queries) GetSubscriberByID(ctx context.Context, id pgtype.UUID) (Subscriber, error) {
	row := q.db.QueryRow(ctx, getSubscriberByID, id)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EndpointUrl,
		&i.AuthSecret,
		&i.MaxParallel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionsMatchingSubject = `-- name: GetSubscriptionsMatchingSubject :many
SELECT id, subscriber_id, subject_pattern, filter, max_retries, created_at, updated_at FROM subscriptions WHERE $1 LIKE replace(replace(subject_pattern, '*', '%'), '?', '_')
`

func (q *Queries) GetSubscriptionsMatchingSubject(ctx context.Context, subjectPattern string) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, getSubscriptionsMatchingSubject, subjectPattern)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.SubscriberID,
			&i.SubjectPattern,
			&i.Filter,
			&i.MaxRetries,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscribers = `-- name: ListSubscribers :many
SELECT id, name, endpoint_url, auth_secret, max_parallel, created_at, updated_at FROM subscribers ORDER BY created_at DESC
`

func (q *Queries) ListSubscribers(ctx context.Context) ([]Subscriber, error) {
	rows, err := q.db.Query(ctx, listSubscribers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscriber
	for rows.Next() {
		var i Subscriber
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EndpointUrl,
			&i.AuthSecret,
			&i.MaxParallel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsForSubscriber = `-- name: ListSubscriptionsForSubscriber :many
SELECT id, subscriber_id, subject_pattern, filter, max_retries, created_at, updated_at FROM subscriptions WHERE subscriber_id = $1 ORDER BY created_at
`

func (q *Queries) ListSubscriptionsForSubscriber(ctx context.Context, subscriberID pgtype.UUID) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsForSubscriber, subscriberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.SubscriberID,
			&i.SubjectPattern,
			&i.Filter,
			&i.MaxRetries,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSubscriber = `-- name: UpsertSubscriber :one
INSERT INTO subscribers (id, name, endpoint_url, auth_secret, max_parallel, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, now(), now())
ON CONFLICT (endpoint_url) DO UPDATE SET
    name = EXCLUDED.name,
    auth_secret = EXCLUDED.auth_secret,
    max_parallel = EXCLUDED.max_parallel,
    updated_at = now()
RETURNING id, name, endpoint_url, auth_secret, max_parallel, created_at, updated_at
`

type UpsertSubscriberParams struct {
	ID          pgtype.UUID
	Name        string
	EndpointUrl string
	AuthSecret  string
	MaxParallel int32
}

func (q *Queries) UpsertSubscriber(ctx context.Context, arg UpsertSubscriberParams) (Subscriber, error) {
	row := q.db.QueryRow(ctx, upsertSubscriber,
		arg.ID,
		arg.Name,
		arg.EndpointUrl,
		arg.AuthSecret,
		arg.MaxParallel,
	)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EndpointUrl,
		&i.AuthSecret,
		&i.MaxParallel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
